# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Mateus
title: "Mateus' Blog"
email: mateus.rodrigues@live.com
description: > # this means to ignore newlines until "baseurl:"
  Developer, engineer-to-be and technology enthusiast.
  Co-Founder @ <a href="http://orbt.tech" target="_blank">Orbt</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.mateus.tech" # the base hostname & protocol for your site, e.g. http://example.com

# theme specific options
author:             "Mateus Rodrigues de Morais"
gravatar_hash:      "44fe99ce1cd07d36f5898383206f1344"
twitter:            "hitech_8"
email:              "mateus.rodrigues@live.com"
github:             "mateusrodrigues"
# pinterest:          "jhondoe"
linkedin:           "mateusrodriguesdemorais"
# facebook:           "johndoe"

# Google services
google_analytics:   # UA-89988992-1

disqus_shortname:   # "mateusrodrigues"

# background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"
background:         "/images/crissxcross.png"

paginate:           5
# paginate_path:      "/page:num/"
paginate_path:      "/:num/"

permalink:          /:year/:month/:day/:title/

nav:
  - name:           "Home"
    href:           "/"
  - name:           "Archives"
    href:           "/archives"
  - name:           "About"
    href:           "/about"

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Webmaster Verifications
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234

# Build settings
highlighter: rouge
markdown: kramdown
gems:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts
exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.cmd
  - getruby.cmd
  - README.md