# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Mateus
title: "Mateus's Blog"
email: mateus.rodrigues@live.com
description: > # this means to ignore newlines until "baseurl:"
  Developer, engineer-to-be and technology enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# theme specific options
author:             "mateusrodrigues"
gravatar_hash:      "44fe99ce1cd07d36f5898383206f1344"
twitter:            "hitech_8"
email:              "mateus.rodrigues@live.com"
github:             "mateusrodrigues"
# pinterest:          "jhondoe"
linkedin:           "mateusrodriguesdemorais"
# facebook:           "jhondoe"

disqus_shortname:   "mateus-2"

# background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"
background:         "https://static.pexels.com/photos/2324/skyline-buildings-new-york-skyscrapers.jpg"

paginate:           5
# paginate_path:      "/page:num/"
paginate_path:      "/:num/"

permalink:          /:year/:month/:day/:title/

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Contact"
    href:           "/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
